### ISSUE TITLE
Make plus and minus icons 508 compliant add tab/focus order

### ISSUE THREAD

**Issue by pcapp2114** [AmazeeLabs/paragraphs_collapsible#3]
add tab/focus order to the collapse plus and minus icons. Nice Module!

**Comment by stewest** [comment]
Thanks @pcapp2114  for your issue.  We've moved this to Drupal. https://www.drupal.org/project/paragraphs_collapsible

We'll look into the issue there.

**Comment by stewest** [comment]
https://www.drupal.org/project/paragraphs_collapsible/issues/3013070
